// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wcmwlxidorljeijapkxp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndjbXdseGlkb3JsamVpamFwa3hwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2MjM3NjAsImV4cCI6MjA3MTE5OTc2MH0.fO_iK0bYCu5k99ghs7TCtibpQCVLWujGb2T4EFtIPVY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});